### ISSUE TITLE
Documentaion

### ISSUE THREAD

**Issue by warren-ru** [dennisstritzke/trex_exporter#1]
Could you provide some docs on how to use the exporter?

**Comment by dennisstritzke** [comment]
There is definitely documentation. What information are you specifically missing?

**Comment by warren-ru** [comment]
For those who are not a Go expert could you tell:
1) how to start a service (should a binary from the "Releases" page be used?)?
2) how to provide the service with the miner parameters (address)?

As I can see in the serve.go, we should provide the service with three parameters.

**Comment by warren-ru** [comment]
Ok. Finally, I googled all I need.
